apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-binding
spec:
  type: bindings.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost port=5432 user=postgres password=dapr123 dbname=venuedb sslmode=disable"
